version: '3.9'

services:
  postgres:
    container_name: postgres_auth
    image: postgres
    env_file:
      - ./keycloak/db/keycloak.db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    env_file:
      - ./keycloak/keycloak.env
    depends_on:
      - "postgres"
    ports:
      - "8888:8080"
      - "8787:8787"
    command: start-dev --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true

volumes:
  postgres-data: 
    driver: local
