version: '3.9'

services:
  postgres:
    container_name: postgres_auth
    #build: ./keycloak/db
    image: postgres
    env_file:
      - ./keycloak/db/keycloak.db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - keycloak-db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin_receba
    image: dpage/pgadmin4
    env_file:
      - ./pgadmin/pgadmin.env
    ports:
      - "5050:80"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    env_file:
      - ./keycloak/keycloak.env
    depends_on:
      - "postgres"
    ports:
      - "8080:8080"
      - "8787:8787"
    command: start-dev

volumes:
  postgres-data: {}
  keycloak-db: {}