# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    env_file: ./db/mongo.env
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    command: mongod

#  iniciativas:
#    container_name: servico-iniciativas
#    build:
#      context: iniciativas
#      dockerfile: Dockerfile
#    image: servico-iniciativas
#    restart: always
#    ports:
#      - "8090:8090"
#    depends_on:
#      - mongo

volumes:
  mongo-data:
    driver: local